import pygame

# Game Window Size
COLLUMNS = 10
ROWS = 20
CELL_SIZE = 40
GAME_WIDTH, GAME_HEIGHT = COLLUMNS * CELL_SIZE, ROWS * CELL_SIZE

# Side Bar Size
SIDEBAR_WIDTH = 200
PREVIEW_HEIGHT_FRACTION = 0.7
SCORE_HEIGHT_FRACTION = 1 - PREVIEW_HEIGHT_FRACTION

# Window
PADDING = 20
WINDOW_WIDTH = GAME_WIDTH + SIDEBAR_WIDTH + PADDING * 3
WINDOW_HEIGHT = GAME_HEIGHT + PADDING * 2

# Color
LIGHT_SLATE_GRAY = "#778899"
WHITE = "#FFFFFF"
DARK_GRAY = "#696969"